name: listy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  iconsax: ^0.0.8
  provider: ^6.1.1
  realm: ^1.9.0
  url_launcher: ^6.2.1
  vertical_card_pager: ^1.5.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/produtor/
    - assets/images/cras/
    - assets/images/hortalicias/
    - assets/images/produtores/
    - assets/config/
